# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExamExasyCom' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExamExasyCom
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire', '~> 4.7'

end
